# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 271)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 116, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_firstIm = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_firstIm.setObjectName("lineEdit_firstIm")
        self.gridLayout.addWidget(self.lineEdit_firstIm, 1, 1, 1, 1)
        self.lineEdit_secondRe = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_secondRe.setObjectName("lineEdit_secondRe")
        self.gridLayout.addWidget(self.lineEdit_secondRe, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.lineEdit_firstRe = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_firstRe.setObjectName("lineEdit_firstRe")
        self.gridLayout.addWidget(self.lineEdit_firstRe, 1, 0, 1, 1)
        self.lineEdit_secondIm = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_secondIm.setObjectName("lineEdit_secondIm")
        self.gridLayout.addWidget(self.lineEdit_secondIm, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 20, 77, 117))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_plus = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_plus.setObjectName("radioButton_plus")
        self.verticalLayout.addWidget(self.radioButton_plus)
        self.radioButton_minus = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_minus.setObjectName("radioButton_minus")
        self.verticalLayout.addWidget(self.radioButton_minus)
        self.radioButton_mult = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_mult.setObjectName("radioButton_mult")
        self.verticalLayout.addWidget(self.radioButton_mult)
        self.radioButton_div = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_div.setObjectName("radioButton_div")
        self.verticalLayout.addWidget(self.radioButton_div)
        self.pushButton_calculate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.verticalLayout.addWidget(self.pushButton_calculate)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 20, 121, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_Answer = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_Answer.setObjectName("lineEdit_Answer")
        self.verticalLayout_2.addWidget(self.lineEdit_Answer)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 351, 91))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_thirdRe = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_thirdRe.setGeometry(QtCore.QRect(10, 38, 54, 20))
        self.lineEdit_thirdRe.setObjectName("lineEdit_thirdRe")
        self.lineEdit_thirdIm = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_thirdIm.setGeometry(QtCore.QRect(70, 38, 54, 20))
        self.lineEdit_thirdIm.setObjectName("lineEdit_thirdIm")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(70, 10, 54, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 20, 20))
        self.label_7.setMaximumSize(QtCore.QSize(20, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_Absolute = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Absolute.setGeometry(QtCore.QRect(160, 40, 54, 20))
        self.lineEdit_Absolute.setObjectName("lineEdit_Absolute")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(160, 10, 41, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 100))
        self.label_8.setObjectName("label_8")
        self.lineEdit_Argument = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Argument.setGeometry(QtCore.QRect(250, 40, 54, 20))
        self.lineEdit_Argument.setObjectName("lineEdit_Argument")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(250, 10, 51, 20))
        self.label_9.setMaximumSize(QtCore.QSize(100, 100))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Re"))
        self.label_2.setText(_translate("Form", "Im"))
        self.label_3.setText(_translate("Form", "Re"))
        self.label_4.setText(_translate("Form", "Im"))
        self.radioButton_plus.setText(_translate("Form", "+"))
        self.radioButton_minus.setText(_translate("Form", "-"))
        self.radioButton_mult.setText(_translate("Form", "*"))
        self.radioButton_div.setText(_translate("Form", "/"))
        self.pushButton_calculate.setText(_translate("Form", "Calculate"))
        self.label_5.setText(_translate("Form", "Answer:"))
        self.lineEdit_thirdRe.setText(_translate("Form", "0"))
        self.lineEdit_thirdIm.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "Im"))
        self.label_7.setText(_translate("Form", "Re"))
        self.label_8.setText(_translate("Form", "Absolute"))
        self.label_9.setText(_translate("Form", "Argument"))
